server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/bus_db
spring.datasource.username=root
spring.datasource.password=Adhi@3129

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true